### ISSUE TITLE
Manually report test progress and result

### ISSUE THREAD

**Issue by nighthawk** [DataDog/dd-sdk-swift-testing#47]
We have an internal testing tool written in Swift which is not based on XCTest. I *really* like how Datadog is visualising test results and cross-references tests to server calls being made, and I'm curious if our internal testing tool can be integrated with that.

Looking at `DDTestObserver`, it should be possible to allow manually reporting when a test started, and what the result is when it finished. Currently we'd have to reverse engineer how that observers integrates with XCTest and how it extracts suite name and test name, and then either report like that to `XCTestObservationCenter` or allow our testing tool to run using `XCTestCase` (which is frankly quite painful as they would have to be generated programatically which isn't well documented).

It'd be great if there was a documented/supported way in `DatadogSDKTesting` to support this by providing a public interface that allows reporting when a test started and with what result it finished.

**Comment by nachoBonafonte** [comment]
Hi nighthawk, 

Thanks for the compliments, we are working really hard on the product and love having good feedback, although we also like any other feedback that can help us improve the product.

About your request, it was not in the short term plans to provide something like that, but I think it should not be very difficult for us to provide it as you said. 

The idea is refactoring DDTestObserver class, so it uses the same public interface we will provide. It might bring some XCTest-ism to the interface,  but that will help validating and testing, and will assure that both solutions are totally compatible in the future when more changes are added.

What do you think? Would you be interested in testing and validating the interface/solution while in development with some beta version?

Thanks a lot

**Comment by nachoBonafonte** [comment]
In the related PR I have created a simple API that should be enough for reporting tests programmatically ( I rewrote all the DDTestObserver logic on top of it). Planning to release a beta really soon.

**Comment by nachoBonafonte** [comment]
I have just released a beta version, [0.9.6-beta.1](https://github.com/DataDog/dd-sdk-swift-testing/releases/tag/0.9.6-beta.1) which includes an API for reporting your own tests, the api looks quite simple but I have rewritten the current `DDTestObserver` class on top of it and is used internally now for reporting the XCTests:
```
public DDTestSession {
    static func start(bundleName: String) -> DDTestSession
    func end()

    func suiteStart(name: String) -> DDTestSuite
    func suiteEnd(suite: DDTestSuite)

    func testStart(name: String, suite: DDTestSuite) -> DDTest
    func testSetAttribute(test: DDTest, key: String, value: Any)
    func testSetErrorInfo(test: DDTest, type: String, message: String, callstack: String?)
    func testAddBenchmark(test:DDTest, name: String, samples: [Double], info: String?)
    func testEnd(test: DDTest, status: DDTestStatus)
}

public enum DDTestStatus: Int {
    case pass
    case fail
    case skip
}
```
The basic workflow for the API would be like:
```
let session = DDTestSession.start(bundleName: "ManualSession") //Always call it at the beggining with the name of the bundle which includes the tests

let suite1 = session.suiteStart(name: "ManualSuite 1") // All tests must be part of a suite 

let test1 = session.testStart(name: "Test 1", suite: suite1)
session.testSetAttribute(test: test1, key: "key", value: "value")
session.testEnd(test: test1, status: .pass)

let test2 = session.testStart(name: "Test 2", suite: suite1)
session.testSetErrorInfo(test: test2, type: "Error Type", message: "Error message", callstack: "Optional callstack")
session.testEnd(test: test2, status: .fail)

session.suiteEnd(suite: suite1)

let suite2 = session.suiteStart(name: "ManualSuite 2") 
...

...
session.end() //Always call it at the end so all the test info is flushed to the Datadog servers
```

All the configuration is done in the way it is already documented, and all the instrumentation (Git info, network instrumentation, stdout capturing, ... ) is also started when the DDTestSession is started

**Comment by nachoBonafonte** [comment]
@nighthawk let me know if it covers your use case or if you have some doubt or issue with it

**Comment by nachoBonafonte** [comment]
Hi, I am glad it starts looking good, but as you saw there are still some rough edges that we must fix:

>Firstly, I do get this one runtime error. Is there anything I should do to address this?

That error comes after session is started, it uses the bundleName to locate a loaded library with the same name linked in the process and tries to locate its symbols file (if a dSYM file is generated) or generate a dSYM file if symbols are embedded. 

It first uses the directory defined in DYLD_LIBRARY_PATH environment variable to search for the libraries. It looks like in this case the environment variable is not defining a valid directory. 

The error is not dangerous, but it means that we don't have valid symbol files to fully symbolicate crashes. I have to investigate better how to handle this case, but maybe changing the AP to pass the bundle path instead of just the name could improve things.

>Secondly, is this thread-safe? 

As you saw, it still is not thread safe. That crash comes from the Crash handler code. Currently when a test starts it saves the current test state using `-[PLCrashReporter setCustomData:]` method, so if that test crashes the crash is recovered when the frameworks restarts and the error along with the symbolicated crash stack is send to the backend. 
When several tests start in parallel all of them are modifying the state without synchronisation, which means two things, 
 that sometimes they crash, and that even if it doesn’t crash it is losing the previous test state ( so the previous test crashes wont be properly reported). 
I must work in that area so crash handling can be used concurrently. For the mean time the only options are running tests serially or disable the crash handler by setting  environment DD_DISABLE_CRASH_HANDLER

> One more thing: I noticed that the "Operation Name" on Datadog ends up being "XCTest.test". Is there a way to manually set or overwrite this?

That is an oversight on my side, I will investigate and fix it.  Are there any other tags or values that are reported that are not what you would expect (some of them are probably hardcoded like the "Operation name")

**Comment by nighthawk** [comment]
And one more thing again: The beta version of the SDK doesn't compile on older Swift versions (5.4.2) and also not when building with the latest official Xcode 13 when building for macOS 11 (though it does build with good old Xcode 13 beta 5):

```
/Users/adrian/SkedGo/RoutingSpecKit/Sources/RoutingSpecRunner/RoutingSpecRunner+Run.swift:11:8: error: failed to build module 'DatadogSDKTesting'; this SDK is not supported by the compiler (the SDK is built with 'Apple Swift version 5.5 (swiftlang-1300.0.29.102 clang-1300.0.28.1)', while this compiler is 'Apple Swift version 5.5 (swiftlang-1300.0.31.1 clang-1300.0.29.1)'). Please select a toolchain which matches the SDK.
import DatadogSDKTesting
       ^
/Users/adrian/SkedGo/RoutingSpecKit/.build/arm64-apple-macosx/debug/DatadogSDKTesting.framework/Modules/DatadogSDKTesting.swiftmodule/arm64-apple-macos.swiftinterface:11:8: error: no such module '_Concurrency'
import _Concurrency
```

**Comment by nachoBonafonte** [comment]
Hi @nighthawk, 
We have released version 1.0.2 of the testing framework, but I wanted to warn you that it includes some breaking changes to the Test API.
* `setAttribute()` has been renamed to `setTag()`
* `addBenchmark()` was removed
 This changes were done for consistency with other platforms, but we expect this API to be stable from now on

**Comment by nachoBonafonte** [comment]
Hi @nighthawk,
We just released version [2.1.0](https://github.com/DataDog/dd-sdk-swift-testing/releases/tag/2.1.0) of the framework, and a new API breaking change was needed in advance for new features:
* `DDTestSession` has been renamed to `DDTestModule`

**Comment by nighthawk** [comment]
Thanks for the ping, @nachoBonafonte.

By the way, you can add a `typealias` and mark it as "renamed", which will then make Xcode suggest quick fixes to do the renaming, rather than only showing compile errors that the symbol doesn't exist, e.g.:

```swift
@available(*, unavailable, renamed: "DDTestModule")
public typealias DDTestSession = DDTestModule
```
