### PR TITLE
Fix integration tests in the CI

### PR DESCRIPTION
**Pull request by albertvaka**
- Build on macOS 13 [1] with Xcode 14.3 (latest to support targeting iOS 11, which we want to support)
- Apply recommended project settings update for XCode 14.3
- Fix a flaky test due to sorting of JSON dicts not being guaranteed

Passing pipeline: https://github.com/DataDog/dd-sdk-swift-testing/actions/runs/6469451790

[1] For some reason that I don't understand, even though we are targeting macos 10.13, I was getting compilation errors because of [some macos 13-only code](https://github.com/open-telemetry/opentelemetry-swift/blame/main/Sources/Instrumentation/URLSession/URLSessionInstrumentation.swift#L601-L601C17) in the opentelemetry-swift dependency even when that code is behind an `ifdef` for macos 13+. Instead of trying to solve this, I went ahead and bumped the macos version we build on to 13, which also required bumping Xcode.

### CODE REVIEW

File: .github/workflows/integrationTests.yml [hunk 1]
```diff
@@ -7,18 +7,18 @@ on:
 
 jobs:
 
-  test-12-0-Integration-build:
-    name: Run Tests 12.0
-    runs-on: macos-12
+  test-13-Integration-build:
+    name: Run Tests MacOS 13.0
```
Comment (iGranDav) [inline .github/workflows/integrationTests.yml:11]:
```suggestion
    name: Run Tests macOS 13.0
```
**nit:** feel free to ignore ;)

File: .github/workflows/integrationTests.yml [hunk 2]
```diff
@@ -7,18 +7,18 @@ on:
...
+    runs-on: macos-13
     strategy:
       fail-fast: false
       matrix:
-        xcode: ["13.3.1", "14.0", "14.1", "14.2"]
+        xcode: ["Xcode_14.3"]
```
Comment (iGranDav) [inline .github/workflows/integrationTests.yml:16]: Maybe several Xcode version were selected here to test using several compiler versions. Are we ok dropping those?

**Review by iGranDav — APPROVED** [review]

File: .github/workflows/integrationTests.yml (hunk 2 above)
Comment (albertvaka) [reply .github/workflows/integrationTests.yml]: Only Xcode 14.1 and later are available on the macOS 13 runners (which I had to upgrade to because of the new version of opentelemetry-swift), I can re-add 14.1 and 14.2 though if we want to make sure it continues to build there.

Comment (iGranDav) [reply .github/workflows/integrationTests.yml]: 👍🏼 14.2 and 14.3.1 might make sense since they use two different swift stack https://swiftversion.net/ no need for 14.1.

Comment (albertvaka) [reply .github/workflows/integrationTests.yml]: Do you recommend having both 14.3 and 14.3.1?

Comment (iGranDav) [reply .github/workflows/integrationTests.yml]: Just 14.2 and 14.3.1 should be enough. The later fixed a bug on 14.3 so having both isn't necessary.
